In [65]:
import pandas as pd
import numpy as np

In [66]:
data = pd.read_csv("global-data-on-sustainable-energy.csv")
data.head()

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [67]:
data.isnull().sum()

Entity                                                                 0
Year                                                                   0
Access to electricity (% of population)                               10
Access to clean fuels for cooking                                    169
Renewable-electricity-generating-capacity-per-capita                 931
Financial flows to developing countries (US $)                      2089
Renewable energy share in the total final energy consumption (%)     194
Electricity from fossil fuels (TWh)                                   21
Electricity from nuclear (TWh)                                       126
Electricity from renewables (TWh)                                     21
Low-carbon electricity (% electricity)                                42
Primary energy consumption per capita (kWh/person)                     0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)          207
Value_co2_emissions_kt_by_country                                    428
Renewables (% equivalent primary energy)                            2137
gdp_growth                                                           317
gdp_per_capita                                                       282
Density\n(P/Km2)                                                       1
Land Area(Km2)                                                         1
Latitude                                                               1
Longitude                                                              1
dtype: int64

In [68]:
a = np.zeros(21, dtype="int") 
y = np.zeros(21, dtype="int")


for i in range(21):
    a[i] = len(data[data["Year"] == 2000+i])
    y[i] = 2000+i

pd.DataFrame({"Year":y, "Amount":a})

    Year  Amount
0   2000     173
1   2001     172
2   2002     172
3   2003     172
4   2004     172
5   2005     172
6   2006     172
7   2007     174
8   2008     174
9   2009     174
10  2010     174
11  2011     174
12  2012     174
13  2013     175
14  2014     175
15  2015     175
16  2016     175
17  2017     175
18  2018     175
19  2019     175
20  2020     175

In [69]:
data["Entity"].value_counts()

Entity
Afghanistan            21
Albania                21
Algeria                21
Angola                 21
Antigua and Barbuda    21
                       ..
Uzbekistan             21
Serbia                 14
Montenegro             14
South Sudan             8
French Guiana           1
Name: count, Length: 176, dtype: int64

# Preprocessing

### Cluster Weight Equalizing

In [70]:
entity_counts = data["Entity"].value_counts()

eligible_entities = entity_counts[entity_counts == 21].index
used_df = data[data["Entity"].isin(eligible_entities)]

ineligible_entities = entity_counts[entity_counts != 21].index
unused_df = data[data["Entity"].isin(ineligible_entities)]

In [71]:
unused_df["Entity"].value_counts().sort_index()

Entity
French Guiana     1
Montenegro       14
Serbia           14
South Sudan       8
Name: count, dtype: int64

In [72]:
print("Used Entity Count: ", len(used_df["Entity"].unique()))
used_df["Entity"].value_counts().sort_index()

Used Entity Count:  172

Entity
Afghanistan            21
Albania                21
Algeria                21
Angola                 21
Antigua and Barbuda    21
                       ..
Uzbekistan             21
Vanuatu                21
Yemen                  21
Zambia                 21
Zimbabwe               21
Name: count, Length: 172, dtype: int64

# Dtype Correction

In [73]:
used_df.dtypes

Entity                                                               object
Year                                                                  int64
Access to electricity (% of population)                             float64
Access to clean fuels for cooking                                   float64
Renewable-electricity-generating-capacity-per-capita                float64
Financial flows to developing countries (US $)                      float64
Renewable energy share in the total final energy consumption (%)    float64
Electricity from fossil fuels (TWh)                                 float64
Electricity from nuclear (TWh)                                      float64
Electricity from renewables (TWh)                                   float64
Low-carbon electricity (% electricity)                              float64
Primary energy consumption per capita (kWh/person)                  float64
Energy intensity level of primary energy (MJ/$2017 PPP GDP)         float64
Value_co2_emissions_kt_by_country                                   float64
Renewables (% equivalent primary energy)                            float64
gdp_growth                                                          float64
gdp_per_capita                                                      float64
Density\n(P/Km2)                                                     object
Land Area(Km2)                                                      float64
Latitude                                                            float64
Longitude                                                           float64
dtype: object

In [74]:
used_df['Density\\n(P/Km2)'] = used_df['Density\\n(P/Km2)'].str.replace(",", ".", regex=False).astype(float)

/tmp/ipykernel_4380/1776739077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  used_df['Density\\n(P/Km2)'] = used_df['Density\\n(P/Km2)'].str.replace(",", ".", regex=False).astype(float)

In [75]:
used_df.dtypes

Entity                                                               object
Year                                                                  int64
Access to electricity (% of population)                             float64
Access to clean fuels for cooking                                   float64
Renewable-electricity-generating-capacity-per-capita                float64
Financial flows to developing countries (US $)                      float64
Renewable energy share in the total final energy consumption (%)    float64
Electricity from fossil fuels (TWh)                                 float64
Electricity from nuclear (TWh)                                      float64
Electricity from renewables (TWh)                                   float64
Low-carbon electricity (% electricity)                              float64
Primary energy consumption per capita (kWh/person)                  float64
Energy intensity level of primary energy (MJ/$2017 PPP GDP)         float64
Value_co2_emissions_kt_by_country                                   float64
Renewables (% equivalent primary energy)                            float64
gdp_growth                                                          float64
gdp_per_capita                                                      float64
Density\n(P/Km2)                                                    float64
Land Area(Km2)                                                      float64
Latitude                                                            float64
Longitude                                                           float64
dtype: object

## Missing Value Imputation

In [76]:
used_df.isnull().sum()

Entity                                                                 0
Year                                                                   0
Access to electricity (% of population)                                9
Access to clean fuels for cooking                                    168
Renewable-electricity-generating-capacity-per-capita                 903
Financial flows to developing countries (US $)                      2058
Renewable energy share in the total final energy consumption (%)     191
Electricity from fossil fuels (TWh)                                   21
Electricity from nuclear (TWh)                                       126
Electricity from renewables (TWh)                                     21
Low-carbon electricity (% electricity)                                42
Primary energy consumption per capita (kWh/person)                     0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)          199
Value_co2_emissions_kt_by_country                                    424
Renewables (% equivalent primary energy)                            2100
gdp_growth                                                           311
gdp_per_capita                                                       276
Density\n(P/Km2)                                                       0
Land Area(Km2)                                                         0
Latitude                                                               0
Longitude                                                              0
dtype: int64

In [77]:
used_df = used_df.drop([
                "Financial flows to developing countries (US $)",
                "Renewables (% equivalent primary energy)",
                "Renewable-electricity-generating-capacity-per-capita"
                ], axis = 1) # Too many missing values

used_df = used_df.drop(['gdp_growth'], axis=1)

In [78]:
used_df.isnull().sum()

Entity                                                                0
Year                                                                  0
Access to electricity (% of population)                               9
Access to clean fuels for cooking                                   168
Renewable energy share in the total final energy consumption (%)    191
Electricity from fossil fuels (TWh)                                  21
Electricity from nuclear (TWh)                                      126
Electricity from renewables (TWh)                                    21
Low-carbon electricity (% electricity)                               42
Primary energy consumption per capita (kWh/person)                    0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)         199
Value_co2_emissions_kt_by_country                                   424
gdp_per_capita                                                      276
Density\n(P/Km2)                                                      0
Land Area(Km2)                                                        0
Latitude                                                              0
Longitude                                                             0
dtype: int64

In [79]:
cols = used_df.columns[2:]
print(cols)

for col in cols:
    used_df[col] = used_df.groupby("Entity")[col].transform(lambda x: x.interpolate(method="linear", limit_direction="both"))

Index(['Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       'Renewable energy share in the total final energy consumption (%)',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
       'Value_co2_emissions_kt_by_country', 'gdp_per_capita',
       'Density\n(P/Km2)', 'Land Area(Km2)', 'Latitude', 'Longitude'],
      dtype='object')

In [80]:
used_df.isnull().sum()

Entity                                                                0
Year                                                                  0
Access to electricity (% of population)                               0
Access to clean fuels for cooking                                   168
Renewable energy share in the total final energy consumption (%)     21
Electricity from fossil fuels (TWh)                                  21
Electricity from nuclear (TWh)                                      126
Electricity from renewables (TWh)                                    21
Low-carbon electricity (% electricity)                               42
Primary energy consumption per capita (kWh/person)                    0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)          21
Value_co2_emissions_kt_by_country                                   252
gdp_per_capita                                                      231
Density\n(P/Km2)                                                      0
Land Area(Km2)                                                        0
Latitude                                                              0
Longitude                                                             0
dtype: int64

Since every missing value is multiple of 21, it is assumed that these values cannot be interpolated. So, those columns will be dropped.

In [81]:
print(used_df.shape)
used_df = used_df.dropna()
print(used_df.shape)
used_df.isnull().sum()

(3612, 17)
(3045, 17)

Entity                                                              0
Year                                                                0
Access to electricity (% of population)                             0
Access to clean fuels for cooking                                   0
Renewable energy share in the total final energy consumption (%)    0
Electricity from fossil fuels (TWh)                                 0
Electricity from nuclear (TWh)                                      0
Electricity from renewables (TWh)                                   0
Low-carbon electricity (% electricity)                              0
Primary energy consumption per capita (kWh/person)                  0
Energy intensity level of primary energy (MJ/$2017 PPP GDP)         0
Value_co2_emissions_kt_by_country                                   0
gdp_per_capita                                                      0
Density\n(P/Km2)                                                    0
Land Area(Km2)                                                      0
Latitude                                                            0
Longitude                                                           0
dtype: int64

In [82]:
print("Final Entity Count: ", len(used_df["Entity"].unique()))
print("Data Shape: ", used_df.shape)
used_df["Entity"].value_counts().sort_index()

Final Entity Count:  145
Data Shape:  (3045, 17)

Entity
Afghanistan            21
Algeria                21
Angola                 21
Antigua and Barbuda    21
Argentina              21
                       ..
Uruguay                21
Uzbekistan             21
Vanuatu                21
Zambia                 21
Zimbabwe               21
Name: count, Length: 145, dtype: int64

# Save to CSV

In [83]:
used_df.to_csv('cleaned_dataset.csv', index=False)